# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser --ozone-plaform=wayland --enable-features=UseOzonePlatform --ozone-platform-hint=auto --enable-wayland-ime --force-device-scale-factor=0.8
bindd = SUPER SHIFT, M, Qobuz, exec, omarchy-launch-or-focus-webapp Qobuz "https://play.qobuz.com/discover" 
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, slash, Passwords, exec, uwsm app -- 1password

bindd = SUPER SHIFT, W, Force kill active window, killactive
bindd = SUPER SHIFT, S, Slack, exec, omarchy-launch-or-focus-webapp Slack "https://app.slack.com/client/TJTRKF5J4/D05A9G33SUE"

bindd = SUPER SHIFT ALT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, A, Claude, exec, omarchy-launch-webapp "https://claude.ai"

bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = SUPER SHIFT ALT, Y, Twitch, exec, omarchy-launch-or-focus-webapp Twitch "https://twitch.com/directory/following"

bind = SUPER SHIFT, I, exec, /home/max/.scripts/inbox-prompt.sh

# Resizing windows 
bind = SUPER SHIFT CTRL, left, resizeactive, -100 0
bind = SUPER SHIFT CTRL, right, resizeactive, 100 0
bind = SUPER SHIFT CTRL, up, resizeactive, 0 -30
bind = SUPER SHIFT CTRL, down, resizeactive, 0 30

# Toggling scrolling modes between centered 60% and un-centered 50%
bind = SUPER SHIFT, L, exec, ~/.scripts/toggle_scrolling_mode.sh

# Resizing all column in Scrolling layout
# bind = SUPER SHIFT, L, layoutmsg, colresize all 0.6
# bind = SUPER SHIFT CTRL, L, layoutmsg, colresize all 0.33
# bind = SUPER SHIFT CTRL ALT, L, layoutmsg, colresize all 0.5

# Cycling through all workspaces, across all monitors
# Limiting the cycling to the current monitor only: m-1 and m+1 instead of e-1 and e+1
bind = SUPER ALT, left, workspace, e-1
bind = SUPER ALT, right, workspace, e+1

# Moving the active workspace to next monitor
bind = SUPER CTRL SHIFT, up, movecurrentworkspacetomonitor, +1
bind = SUPER CTRL SHIFT, down, movecurrentworkspacetomonitor, -1


# Setting up zoom with mouse wheel
unbind = SUPER, mouse_up # by default, these 2 cycle through workspaces
unbind = SUPER, mouse_down
bind = SUPER SHIFT, mouse_up, exec, hyprctl keyword cursor:zoom_factor 1
bind = SUPER SHIFT, mouse_down, exec, hyprctl keyword cursor:zoom_factor 2

# Voxtype . Should be default with Omarchy, but for some reasion it did not work...
bind = SUPER CTRL, X, exec, voxtype record toggle 
